services:
  - type: web
    name: notfliz
    runtime: go
    rootDirectory: server
    buildCommand: go build -o app .
    startCommand: ./app
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
